version: '2'

services:
  
  crypto-miner:
    image: sikkienl/cpuminer
    container_name: crypto-miner
    environment:
      - ALGO=neoscrypt
      - URL=stratum+tcp://pool.neobytes.network:3010
      - USER=NQ6Mi4my7vFVTXvhicVSNF2MSRqPdwYAvH.worker1
      - PASS=x
      - THREADS=2
    restart: always
