name: Docker Miner Image 

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  NAME: sikkienl
  IMAGE_NAME: sikkienl/cpuminer

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Run Docker build ${{ env.NAME }}:latest
        run: |
          docker buildx build --no-cache --platform linux/amd64 \
          --tag ${{ env.IMAGE_NAME }}:latest \
          --output "type=registry" .
